#!/usr/bin/env bash
# kt66 agent layer 자동 구성 — SubAgent × N + Manager
#
# 호출:
#   bash agent/setup-agents.sh           # 자동 (cmd_up 의 마지막 단계)
#   bash agent/setup-agents.sh --skip    # SubAgent 만, Manager skip
#
# 산출물:
#   - 5+ 컨테이너의 :8002 에 SubAgent 가동 (A2A 프로토콜)
#   - 호스트의 :9200 에 Manager (완전 bastion) 가동
#
# 멱등성: 이미 가동된 SubAgent / Manager 가 있으면 stop 후 재가동.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$HERE")"
SKIP_MANAGER=0
[ "${1:-}" = "--skip" ] && SKIP_MANAGER=1

# ── SubAgent 배포 ───────────────────────────────────────────────────
# 대상: Manager 의 worker 가 필요한 5 컨테이너 (bastion 제외 — Manager 본인).
# 멱등: 컨테이너의 entrypoint 에서 영구 가동 중인 경우 skip. 없으면 ad-hoc 가동.
echo "[kt66-agents] (1/3) deploy SubAgent → 5 컨테이너 (bastion 제외 — Manager 본인)"

CONTAINERS=(kt66-attacker kt66-fw kt66-ips kt66-web kt66-siem)

for c in "${CONTAINERS[@]}"; do
    if ! docker ps --format '{{.Names}}' | grep -q "^$c\$"; then
        echo "  $c: SKIP (not running)"
        continue
    fi
    role="${c#kt66-}"

    # 0) 이미 가동 중이면 skip (entrypoint 영구 가동분 보호)
    if docker exec "$c" curl -s --max-time 1 http://127.0.0.1:8002/health 2>/dev/null | grep -q healthy; then
        echo "  $c: already healthy (skip — entrypoint 영구 또는 직전 가동)"
        continue
    fi

    # 1) 코드 cp
    docker cp "$HERE/subagent.py" "$c:/tmp/subagent.py" 2>/dev/null

    # 2) ad-hoc 가동 (entrypoint 미반영 컨테이너 fallback)
    #    trap + exec + subagent.py 의 SIGHUP ignore = 3중 격리
    docker exec -d "$c" bash -c \
        "trap '' HUP TERM; export CCC_ROLE=$role; exec python3 /tmp/subagent.py >> /tmp/subagent.log 2>&1 < /dev/null"

    # 3) 헬스
    sleep 1
    if result=$(docker exec "$c" curl -s --max-time 2 http://127.0.0.1:8002/health 2>/dev/null); then
        echo "  $c: $result (ad-hoc — entrypoint 정착 권장)"
    else
        echo "  $c: FAIL — /tmp/subagent.log 확인 (entrypoint 정착 필요)"
    fi
done

# ── Manager (완전 bastion) ─────────────────────────────────────────
if [ $SKIP_MANAGER -eq 1 ]; then
    echo "[kt66-agents] (skip) Manager 가동 생략 (--skip)"
    exit 0
fi

echo "[kt66-agents] (2/3) prepare bastion repo (Manager)"

# HOME 이 비어있는 환경(systemd 등)에서 set -u 로 죽지 않도록 fallback.
BASTION_DIR="${BASTION_DIR:-${HOME:-/root}/bastion}"
if [ ! -d "$BASTION_DIR" ]; then
    echo "  clone bastion repo → $BASTION_DIR"
    # timeout 으로 감싸 네트워크 불량 환경에서 'up' 이 무한 대기하지 않게 한다.
    # 실패 시 Manager(:9200)만 건너뛰고 graceful exit (SubAgent 는 이미 가동됨).
    if ! timeout 90 git clone --depth 1 https://github.com/mrgrit/bastion.git "$BASTION_DIR"; then
        rm -rf "$BASTION_DIR"
        echo "  ! bastion repo clone 실패/타임아웃 — Manager(:9200) skip. 네트워크 복구 후 'bash kt66.sh agents' 재시도."
        exit 0
    fi
else
    echo "  pull latest → $BASTION_DIR"
    (cd "$BASTION_DIR" && timeout 30 git pull --ff-only 2>&1 | tail -2) || \
        echo "  pull skip (오프라인/타임아웃 — 기존 코드로 계속)"
fi

cd "$BASTION_DIR"

# venv — guard on pip (not just bin/) so a partial venv (ensurepip 누락 시 bin/ 만 생성) self-heals.
if [ ! -x .venv/bin/pip ]; then
    echo "  create venv"
    rm -rf .venv
    if ! python3 -m venv .venv; then
        echo "  ! venv 생성 실패 — 'sudo apt install -y python3-venv python3-pip' 후 재실행" >&2
        exit 1
    fi
fi
echo "  install requirements (quiet)"
# timeout 으로 감싸 pip 가 네트워크에서 멈춰 'up' 을 막지 않게 한다.
if ! timeout 240 .venv/bin/pip install -q -r requirements.txt; then
    echo "  ! pip install 실패/타임아웃 — Manager(:9200) skip (SubAgent 는 정상). 네트워크 복구 후 'bash kt66.sh agents'."
    exit 0
fi

# .env — 보존 (이미 있으면 미덮어쓰기)
if [ ! -f .env ]; then
    echo "  write default .env"
    cat > .env <<EOF
# kt66 Manager .env (auto-generated by setup-agents.sh)
LLM_BASE_URL=${LLM_BASE_URL:-http://10.20.30.220:11434}
LLM_MANAGER_MODEL=${LLM_MANAGER_MODEL:-gpt-oss:120b}
LLM_SUBAGENT_MODEL=${LLM_SUBAGENT_MODEL:-gemma3:4b}

# kt66 컨테이너 IP (4-tier)
VM_ATTACKER_IP=10.20.30.202
VM_SECU_IP=10.20.30.1
VM_WEB_IP=10.20.32.80
VM_SIEM_IP=10.20.32.100
VM_MANAGER_IP=10.20.30.201

BASTION_API_PORT=9200
BASTION_API_KEY=ccc-api-key-2026
EOF
else
    echo "  .env 보존 (이미 존재)"
fi

# 단독 실행 진입점 — bastion repo 가 ccc repo 없이도 가동되도록
if [ ! -f run-api.py ]; then
    cat > run-api.py <<'EOF'
"""Standalone entry — bastion repo 가 ccc repo 의존성 없이 가동."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import api
import uvicorn
uvicorn.run(api.app, host="0.0.0.0", port=int(os.getenv("BASTION_API_PORT", "9200")))
EOF
fi

# start wrapper — env 로딩 + foreground 실행 (background 는 호출자 책임)
if [ ! -f start.sh ]; then
    cat > start.sh <<'EOF'
#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "$0")")"
source .venv/bin/activate
set -a; source .env; set +a
export PYTHONPATH="$(pwd)"
exec python3 -u run-api.py
EOF
    chmod +x start.sh
fi

echo "[kt66-agents] (3/3) start Manager (Bastion API :9200)"

# 기존 종료
pkill -f run-api.py 2>/dev/null || true
sleep 1

# nohup + setsid background
nohup setsid bash "$BASTION_DIR/start.sh" > /tmp/manager.log 2>&1 < /dev/null &
disown

# 헬스 대기 (최대 8 초)
for i in 1 2 3 4 5 6 7 8; do
    sleep 1
    if curl -s --max-time 1 http://127.0.0.1:9200/health >/dev/null 2>&1; then
        echo "  Manager OK — http://localhost:9200/health (${i}s)"
        break
    fi
    [ $i -eq 8 ] && echo "  Manager FAIL — /tmp/manager.log 확인"
done

echo
echo "[kt66-agents] complete."
echo "  · SubAgent: http://<container>:8002/health (각 컨테이너 내부)"
echo "  · Manager:  http://<vm_ip>:9200/health (호스트)"
echo "  · chat:     curl -H 'X-API-Key: ccc-api-key-2026' http://<vm_ip>:9200/chat"
